spring.application.name=games
# 1. DATABASE & Redis SETUP
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/games_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.data.redis.host=${REDISHOST:localhost}
spring.data.redis.port=${REDISPORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
# 2. HIBERNATE & FLYWAY
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
# 3. PERFORMANCE & PAGINATION LIMITS
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.data.web.pageable.max-page-size=100
# 4. LOGGING
logging.level.com.osamah.games=${LOG_LEVEL:DEBUG}
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
# 5. API KEYS & SECRETS
# NOTE: In a real production environment, these would NEVER be hardcoded.
# I have provided a JWT secret and burner API/Email credentials
# so reviewers can run this project instantly with zero setup.
rawg.api.url=https://api.rawg.io/api
rawg.api.key=${RAWG_API_KEY:7c8c4eb9a8894d0f9f79723d5c04b191}
application.security.jwt.secret-key=${JWT_SECRET:6ba9fc095dbab1ee9c246449a1016be9e7529eeca2d22052ef78e7413ee4f5c1}
application.security.jwt.expiration=604800000
# 6. EMAIL CONFIGURATION
brevo.api.key=${BREVO_API_KEY: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}
brevo.sender.email=${BREVO_SENDER_EMAIL:springemailservice2534@gmail.com}