CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255)             NOT NULL UNIQUE,
    username   VARCHAR(255)             NOT NULL UNIQUE,
    password   VARCHAR(255)             NOT NULL,
    role       VARCHAR(50)              NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE games
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          BIGINT                            DEFAULT 0 NOT NULL,
    slug             VARCHAR(255)             NOT NULL UNIQUE,
    title            VARCHAR(255)             NOT NULL,
    description      TEXT,
    release_date     DATE,
    image_url        VARCHAR(255),
    metacritic_score INTEGER,
    average_score    DOUBLE PRECISION         NOT NULL DEFAULT 0.0,
    total_added      BIGINT                   NOT NULL DEFAULT 0,
    planned_count    BIGINT                   NOT NULL DEFAULT 0,
    playing_count    BIGINT                   NOT NULL DEFAULT 0,
    completed_count  BIGINT                   NOT NULL DEFAULT 0,
    dropped_count    BIGINT                   NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE reviews
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL,
    game_id    BIGINT                   NOT NULL,
    content    TEXT                     NOT NULL,
    rating     INTEGER                  NOT NULL,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_game_review UNIQUE (user_id, game_id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE user_games
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL,
    game_id     BIGINT                   NOT NULL,
    game_status VARCHAR(50)              NOT NULL,
    rating      INTEGER,
    CONSTRAINT fk_user_games_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_games_game FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_game_status UNIQUE (user_id, game_id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE otps
(
    id          BIGSERIAL PRIMARY KEY,
    email       VARCHAR(255)             NOT NULL,
    code        VARCHAR(255)             NOT NULL,
    expiry_date TIMESTAMP WITH TIME ZONE NOT NULL
);

